# Generated by Django 5.1.2 on 2026-03-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('year', models.CharField(blank=True, max_length=8)),
                ('summary', models.TextField(blank=True, help_text='Short description used on cards.')),
                ('description', models.TextField(blank=True, help_text='Full case-study text for the project detail page.')),
                ('hero_image', models.URLField(blank=True, help_text='Large hero image shown on project pages / featured sections.')),
                ('thumbnail_image', models.URLField(blank=True, help_text='Image used on cards; falls back to hero image if empty.')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('short_label', models.CharField(help_text="Label used in tabs and pills, e.g. 'LANDSCAPING'.", max_length=40)),
                ('order_label', models.CharField(help_text="Numeric label such as '01', '02' to display before the name.", max_length=8)),
                ('hero_kicker', models.CharField(blank=True, help_text="Small label above hero title, e.g. 'SERVICE 01'.", max_length=120)),
                ('hero_eyebrow', models.CharField(blank=True, help_text="Secondary small label, e.g. 'EST. 2013'.", max_length=120)),
                ('hero_title', models.CharField(help_text="Main hero heading, e.g. 'Ready to Transform Your Landscape?'.", max_length=200)),
                ('hero_emphasis', models.CharField(blank=True, help_text='Optional emphasised word in the hero heading.', max_length=120)),
                ('hero_intro', models.TextField(blank=True, help_text='Short paragraph under the hero title.')),
                ('hero_background_image', models.URLField(blank=True, help_text='Full URL to the hero background image.')),
                ('overview_heading', models.CharField(blank=True, help_text="Overview section heading, e.g. 'Where Nature Becomes Art'.", max_length=200)),
                ('overview_body_primary', models.TextField(blank=True)),
                ('overview_body_secondary', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(default='EXPLORE SERVICE', help_text='Label for primary hero CTA button.', max_length=80)),
                ('cta_secondary_label', models.CharField(default='VIEW PROJECTS', help_text='Label for secondary hero CTA button.', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_hero', models.BooleanField(default=False, help_text='If true, can be used as hero/banner image.')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myApp.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myApp.service'),
        ),
    ]
