# Generated by Django 5.1.2 on 2026-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('cloudinary_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        # NOTE:
        # We intentionally skip altering the 'is_featured' field here because the
        # production database already uses a column named 'featured'. The model
        # now points to that existing column via db_column='featured', so no
        # schema change is required.
    ]
