# Generated by Django 4.2.29 on 2026-03-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_project_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on listing cards.')),
                ('category', models.CharField(choices=[('interior', 'Interior Design'), ('landscape', 'Landscaping'), ('joinery', 'Joinery'), ('pools', 'Swimming Pools'), ('guides', 'Project Guides'), ('dubai', 'Dubai Living')], default='interior', max_length=20)),
                ('cover_image_url', models.URLField(blank=True, help_text='Full URL to the article cover/hero image.')),
                ('blocks', models.JSONField(blank=True, default=dict, help_text='Editor.js blocks JSON — the full article body.')),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes.')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin as the featured article on the insights listing page.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='public_id',
            field=models.CharField(help_text='Cloudinary public_id identifier', max_length=255),
        ),
    ]
